### PR TITLE
New Simulation button is op

### LINKED ISSUE #112: Fix "New Simulation" button
It's broken because of the simulation loop.

We just need to make it so the button doesn't close the window itself. It must tell the loop to stop, and then close the window.

### LINKED ISSUE #121: Add pause, increase and decrease option to the simulation

### PR DESCRIPTION
**Pull request by texx94**
fixes #112, closes #121

### CODE REVIEW

**Comment by Laykel** [comment]
It doesn't look bad, but I'm afraid our code base is starting to look like an Italian dish.

Could maybe @Waltharnack or @mtutic tell us what they think about it?

**Comment by texx94** [comment]
By the way Closes #121

**Comment by Laykel** [comment]
Nice job on that last update. I approve, but sadly Travis seems to be dead... :skull:

**Comment by Laykel** [comment]
Great. Merging now. 

Sorry for the sloppy job before.

**Pull request merged**
