### PR TITLE
More natural enum representation, french gui

### LINKED ISSUE #80: is the project in french or in english?
the windows's labels are in french but the controler's name and the scenario's name are in english

### LINKED ISSUE #84: Is it necessary to return a list of string in enum?
What GUI team need is just a toString because of the public visibility of Enum. So in order to set our GUI we just make :

```
for (VehicleBehaviourType vb : VehicleBehaviourType.values()) {
    // call toString for each object
    behaviorSelector.addItem(vb);
}
```

### PR DESCRIPTION
**Pull request by Laykel**
Fixes #80, fixes #84

### CODE REVIEW

**Comment by Waltharnack** [comment]
Seems about right, config_path will needs to change. We need an autonomous controller XML too

**Comment by Waltharnack** [comment]
Do you accept my modification ?

**Comment by Laykel** [comment]
Looks about right. Only problem is that the tests have the wrong path, and Travis isn't happy. ^^

**Comment by Waltharnack** [comment]
Let's do it with /config/ for now @Laykel

**Pull request merged**
