### PR TITLE
Remove factory

### PR DESCRIPTION
**Pull request by Waltharnack**

### CODE REVIEW

**Comment by Laykel** [comment]
Are you sure you want to add the scale of the representation in this PR?

**Comment by Waltharnack** [comment]
It's an error... sorry

**Comment by Laykel** [comment]
No worries, do you still want to merge. We can keep those changes for now, it's no big deal.

**Comment by Waltharnack** [comment]
I have reverted those changes. Reverted commits are include in commit history... @Laykel

**Comment by Laykel** [comment]
Great, that works. :+1:

**Pull request merged**
