### PR TITLE
Add itinerary to vehicle

### PR DESCRIPTION
**Pull request by Waltharnack**

### CODE REVIEW

**Comment by Waltharnack** [comment]
Need your opinion on this work @Laykel

**Comment by Waltharnack** [comment]
Maybe it would be more clean to push this code up to an abstract class of which vehicle would inherit.

**Comment by Laykel** [comment]
A few remarks / questions:

1. Don't forget `@throws` clauses in `ItineraryPath`'s constructor.
2. Why does a vehicle have a list of itineraries? (Do we divide an itinerary in small parts?)
3. What would be the name of the abstract superclass you propose? I guess we could create a `Routable` abstract class or such that implements this, yes.

**Comment by Waltharnack** [comment]
1. I forgot it, nice catch
2. Exactly, we subdivide the itinerary in multiple path to have each "movements" that the vehicle will follow on the screen
3. Something like that would be good

Note : when we have a map, we can possibly add an itineraryPath constructor taking a lane segment

**Comment by Waltharnack** [comment]
If m/px ratio can change on the fly, it would make more sense to have than in m.

**Comment by Laykel** [comment]
I don't think we'll have a changing m/px ratio during execution of the scenario anytime soon. Let's start small.

2. That sounds good. We'll see if it's scalable (probably not, but we need to start somewhere).
3. If no other class is going to be "routable", we had better keep everything in Vehicle. We'll create an abstract class if this feature is to be shared.

**Pull request merged**
